import {
  Armchair,
  Baby,
  Bath,
  Bed,
  BedDouble,
  Briefcase,
  Car,
  DoorOpen,
  Dumbbell,
  Gamepad2,
  Lightbulb,
  Music,
  Sofa,
  Trees,
  Tv,
  UtensilsCrossed,
  WashingMachine,
  Waves,
  type LucideIcon,
} from "lucide-react";

// Maps Hue API v2 room/zone archetypes (snake_case) to an icon. Falls back to a
// generic bulb for anything unmapped.
const ICON_BY_ARCHETYPE: Record<string, LucideIcon> = {
  living_room: Sofa,
  lounge: Sofa,
  man_cave: Tv,
  tv: Tv,
  bedroom: BedDouble,
  kids_bedroom: Bed,
  guest_room: BedDouble,
  nursery: Baby,
  bathroom: Bath,
  toilet: Bath,
  kitchen: UtensilsCrossed,
  dining: UtensilsCrossed,
  office: Briefcase,
  studio: Briefcase,
  computer: Briefcase,
  reading: Armchair,
  music: Music,
  gym: Dumbbell,
  recreation: Gamepad2,
  garage: Car,
  carport: Car,
  driveway: Car,
  garden: Trees,
  terrace: Trees,
  balcony: Trees,
  porch: Trees,
  barbecue: Trees,
  pool: Waves,
  hallway: DoorOpen,
  front_door: DoorOpen,
  staircase: DoorOpen,
  laundry_room: WashingMachine,
};

export const getRoomIcon = (archetype: string): LucideIcon =>
  ICON_BY_ARCHETYPE[archetype] ?? Lightbulb;
